"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import linkcancellederror as shared_linkcancellederror
from ..shared import linkcancelledresponse as shared_linkcancelledresponse
from typing import Optional



@dataclasses.dataclass
class CancelPaymentLinkRequest:
    link_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'link_id', 'style': 'simple', 'explode': False }})
    x_client_id: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-id', 'style': 'simple', 'explode': False }})
    x_client_secret: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-secret', 'style': 'simple', 'explode': False }})
    x_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class CancelPaymentLinkResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    headers: Optional[dict[str, list[str]]] = dataclasses.field(default=None)
    link_cancelled_error: Optional[shared_linkcancellederror.LinkCancelledError] = dataclasses.field(default=None)
    r"""Cannot cancel Payment Link if status is not ACTIVE"""
    link_cancelled_response: Optional[shared_linkcancelledresponse.LinkCancelledResponse] = dataclasses.field(default=None)
    r"""Payment Link cancelled"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

