"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import createlinkrequest as shared_createlinkrequest
from ..shared import linkresponse as shared_linkresponse
from typing import Optional



@dataclasses.dataclass
class CreatePaymentLinkRequest:
    x_client_id: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-id', 'style': 'simple', 'explode': False }})
    x_client_secret: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-secret', 'style': 'simple', 'explode': False }})
    create_link_request: Optional[shared_createlinkrequest.CreateLinkRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    x_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class CreatePaymentLinkResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    headers: Optional[dict[str, list[str]]] = dataclasses.field(default=None)
    link_response: Optional[shared_linkresponse.LinkResponse] = dataclasses.field(default=None)
    r"""Payment Link created"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

