"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apierror as shared_apierror
from ..shared import authenticationerror as shared_authenticationerror
from ..shared import createorderbackendrequest as shared_createorderbackendrequest
from ..shared import errorresponse as shared_errorresponse
from ..shared import ordersentity as shared_ordersentity
from ..shared import ratelimiterror as shared_ratelimiterror
from typing import Optional



@dataclasses.dataclass
class CreateOrderRequest:
    x_client_id: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-id', 'style': 'simple', 'explode': False }})
    x_client_secret: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-secret', 'style': 'simple', 'explode': False }})
    create_order_backend_request: Optional[shared_createorderbackendrequest.CreateOrderBackendRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    x_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class CreateOrderResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_error: Optional[shared_apierror.APIError] = dataclasses.field(default=None)
    r"""API related Errors"""
    authentication_error: Optional[shared_authenticationerror.AuthenticationError] = dataclasses.field(default=None)
    r"""Authentication Error"""
    error_response: Optional[shared_errorresponse.ErrorResponse] = dataclasses.field(default=None)
    r"""Any bad or invalid request will lead to following error object"""
    headers: Optional[dict[str, list[str]]] = dataclasses.field(default=None)
    orders_entity: Optional[shared_ordersentity.OrdersEntity] = dataclasses.field(default=None)
    r"""OK"""
    rate_limit_error: Optional[shared_ratelimiterror.RateLimitError] = dataclasses.field(default=None)
    r"""Rate Limit Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

