"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import errorresponse as shared_errorresponse
from ..shared import fetchallsavedinstruments as shared_fetchallsavedinstruments
from enum import Enum
from typing import Optional

class FetchAllSavedInstrumentsInstrumentType(str, Enum):
    r"""type to instrument to query"""
    CARD = 'card'



@dataclasses.dataclass
class FetchAllSavedInstrumentsRequest:
    customer_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'customer_id', 'style': 'simple', 'explode': False }})
    instrument_type: FetchAllSavedInstrumentsInstrumentType = dataclasses.field(metadata={'query_param': { 'field_name': 'instrument_type', 'style': 'form', 'explode': True }})
    r"""type to instrument to query"""
    x_client_id: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-id', 'style': 'simple', 'explode': False }})
    x_client_secret: str = dataclasses.field(metadata={'header': { 'field_name': 'x-client-secret', 'style': 'simple', 'explode': False }})
    x_api_version: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class FetchAllSavedInstrumentsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    error_response: Optional[shared_errorresponse.ErrorResponse] = dataclasses.field(default=None)
    r"""Any bad or invalid request will lead to following error object"""
    fetch_all_saved_instruments: Optional[list[shared_fetchallsavedinstruments.FetchAllSavedInstruments]] = dataclasses.field(default=None)
    r"""OK"""
    headers: Optional[dict[str, list[str]]] = dataclasses.field(default=None)
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

