"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import errorresponse as shared_errorresponse
from ...models.shared import orderpayrequest as shared_orderpayrequest
from ...models.shared import orderpayresponse as shared_orderpayresponse
from typing import Dict, List, Optional


@dataclasses.dataclass
class OrderPayRequest:
    x_api_version: str = dataclasses.field(metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    order_pay_request: Optional[shared_orderpayrequest.OrderPayRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class OrderPayResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    error_response: Optional[shared_errorresponse.ErrorResponse] = dataclasses.field(default=None)
    r"""Any bad or invalid request will lead to following error object"""
    headers: Optional[Dict[str, List[str]]] = dataclasses.field(default=None)
    order_pay_response: Optional[shared_orderpayresponse.OrderPayResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

