"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import errorresponse as shared_errorresponse
from ..shared import otprequest as shared_otprequest
from ..shared import otpresponseentity as shared_otpresponseentity
from typing import Dict, List, Optional


@dataclasses.dataclass
class OTPRequestRequest:
    payment_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'payment_id', 'style': 'simple', 'explode': False }})
    otp_request: Optional[shared_otprequest.OTPRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    x_api_version: Optional[str] = dataclasses.field(default='2022-09-01', metadata={'header': { 'field_name': 'x-api-version', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class OTPRequestResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    error_response: Optional[shared_errorresponse.ErrorResponse] = dataclasses.field(default=None)
    r"""Any bad or invalid request will lead to following error object"""
    headers: Optional[Dict[str, List[str]]] = dataclasses.field(default=None)
    otp_response_entity: Optional[shared_otpresponseentity.OTPResponseEntity] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

