"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import app as shared_app
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class AppPaymentMethod:
    app: shared_app.App = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('app') }})
    

