"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import cardlessemi as shared_cardlessemi
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CardlessEMIPaymentMethod:
    cardless_emi: shared_cardlessemi.CardlessEMI = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cardless_emi') }})
    

