"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from pg_latest import utils
from typing import Optional

class CashbackDetailsCashbackType(str, Enum):
    r"""Type of discount"""
    FLAT = 'flat'
    PERCENTAGE = 'percentage'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CashbackDetails:
    max_cashback_amount: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('max_cashback_amount') }})
    r"""Maximum Value of Cashback allowed."""
    cashback_type: Optional[CashbackDetailsCashbackType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cashback_type'), 'exclude': lambda f: f is None }})
    r"""Type of discount"""
    cashback_value: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cashback_value'), 'exclude': lambda f: f is None }})
    r"""Value of Discount."""
    

