"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateTerminalRequest:
    terminal_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_name') }})
    r"""terminal name to be assigned by merchants"""
    terminal_phone_no: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_phone_no') }})
    r"""phone number assigned to the terminal"""
    terminal_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_id'), 'exclude': lambda f: f is None }})
    r"""merchant’s internal terminal id"""
    

