"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import offerdetails as shared_offerdetails
from ..shared import offermeta as shared_offermeta
from ..shared import offertnc as shared_offertnc
from ..shared import offervalidations as shared_offervalidations
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateOfferBackendRequest:
    offer_details: shared_offerdetails.OfferDetails = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_details') }})
    offer_meta: shared_offermeta.OfferMeta = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_meta') }})
    offer_tnc: shared_offertnc.OfferTnc = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_tnc') }})
    offer_validations: shared_offervalidations.OfferValidations = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_validations') }})
    

