"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LinkNotifyEntity:
    send_email: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('send_email'), 'exclude': lambda f: f is None }})
    r"""If \\"true\\", Cashfree will send email on customer_email"""
    send_sms: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('send_sms'), 'exclude': lambda f: f is None }})
    r"""If \\"true\\", Cashfree will send sms on customer_phone"""
    

