"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class LinkMetaEntity:
    notify_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('notify_url'), 'exclude': lambda f: f is None }})
    r"""Notification URL for server-server communication. It should be an https URL."""
    payment_methods: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_methods'), 'exclude': lambda f: f is None }})
    r"""Allowed payment modes for this link. Pass comma-separated values among following options - \\"cc\\", \\"dc\\", \\"ccc\\", \\"ppc\\", \\"nb\\", \\"upi\\", \\"paypal\\", \\"app\\". Leave it blank to show all available payment methods"""
    return_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('return_url'), 'exclude': lambda f: f is None }})
    r"""The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250."""
    upi_intent: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('upi_intent'), 'exclude': lambda f: f is None }})
    r"""If \\"true\\", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere"""
    

