"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .netbanking import Netbanking
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class NetBankingPaymentMethod:
    netbanking: Netbanking = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('netbanking') }})
    

