"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import cashbackdetails as shared_cashbackdetails
from ..shared import discountdetails as shared_discountdetails
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from pg_latest import utils
from typing import Optional

class OfferDetailsOfferType(str, Enum):
    r"""Offer Type for the Offer."""
    DISCOUNT = 'DISCOUNT'
    CASHBACK = 'CASHBACK'
    DISCOUNT_AND_CASHBACK = 'DISCOUNT_AND_CASHBACK'
    NO_COST_EMI = 'NO_COST_EMI'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OfferDetails:
    offer_type: OfferDetailsOfferType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_type') }})
    r"""Offer Type for the Offer."""
    cashback_details: Optional[shared_cashbackdetails.CashbackDetails] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cashback_details'), 'exclude': lambda f: f is None }})
    discount_details: Optional[shared_discountdetails.DiscountDetails] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('discount_details'), 'exclude': lambda f: f is None }})
    

