"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import upioffer as shared_upioffer
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OfferUPI:
    upi: shared_upioffer.UPIOffer = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('upi') }})
    

