"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from pg_latest import utils

class OfferTncOfferTncType(str, Enum):
    r"""TnC Type for the Offer. It can be either `text` or `link`"""
    LINK = 'link'
    POST = 'post'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OfferTnc:
    offer_tnc_type: OfferTncOfferTncType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_tnc_type') }})
    r"""TnC Type for the Offer. It can be either `text` or `link`"""
    offer_tnc_value: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_tnc_value') }})
    r"""TnC for the Offer."""
    

