"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OfferMeta:
    offer_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_code') }})
    r"""Unique identifier for the Offer."""
    offer_description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_description') }})
    r"""Description for the Offer."""
    offer_end_time: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_end_time') }})
    r"""Expiry Time for the Offer"""
    offer_start_time: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_start_time') }})
    r"""Start Time for the Offer"""
    offer_title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_title') }})
    r"""Title for the Offer."""
    

