"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Any, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OfferValidations:
    max_allowed: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('max_allowed') }})
    r"""Maximum amount of Offer that can be availed."""
    payment_method: Any = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_method') }})
    min_amount: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('min_amount'), 'exclude': lambda f: f is None }})
    r"""Minimum Amount for Offer to be Applicable"""
    

