"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .apppaymentmethod import AppPaymentMethod
from .cardemipaymentmethod import CardEMIPaymentMethod
from .cardlessemipaymentmethod import CardlessEMIPaymentMethod
from .cardpaymentmethod import CardPaymentMethod
from .netbankingpaymentmethod import NetBankingPaymentMethod
from .paylaterpaymentmethod import PaylaterPaymentMethod
from .upipaymentmethod import UPIPaymentMethod
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional, Union


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrderPayRequest:
    payment_method: Union[CardPaymentMethod, UPIPaymentMethod, NetBankingPaymentMethod, AppPaymentMethod, CardEMIPaymentMethod, CardlessEMIPaymentMethod, PaylaterPaymentMethod] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_method') }})
    payment_session_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_session_id') }})
    offer_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offer_id'), 'exclude': lambda f: f is None }})
    r"""This is required if any offers needs to be applied to the order."""
    save_instrument: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('save_instrument'), 'exclude': lambda f: f is None }})
    

