"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrderMeta:
    notify_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('notify_url'), 'exclude': lambda f: f is None }})
    r"""Notification URL for server-server communication. Useful when user's connection drops while re-directing. NotifyUrl should be an https URL. Maximum length: 250."""
    payment_methods: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_methods'), 'exclude': lambda f: f is None }})
    r"""Allowed payment modes for this order. Pass comma-separated values among following options - \\"cc\\", \\"dc\\", \\"ccc\\", \\"ppc\\",\\"nb\\",\\"upi\\",\\"paypal\\",\\"app\\",\\"paylater\\",\\"cardlessemi\\",\\"dcemi\\",\\"ccemi\\",\\"banktransfer\\". Leave it blank to show all available payment methods"""
    return_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('return_url'), 'exclude': lambda f: f is None }})
    r"""The URL to which user will be redirected to after the payment on bank OTP page. Maximum length: 250. The return_url must contain placeholder {order_id}. When redirecting the customer back to the return url from the bank’s OTP page, Cashfree will replace this placeholder with the actual value for that order."""
    

