"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from pg_latest import utils

class OTPRequestAction(str, Enum):
    r"""The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP"""
    SUBMIT_OTP = 'SUBMIT_OTP'
    RESEND_OTP = 'RESEND_OTP'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OTPRequest:
    action: OTPRequestAction = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('action') }})
    r"""The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP"""
    otp: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('otp') }})
    r"""OTP to be submitted"""
    

