"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import paymentmethodappinpaymentsentity as shared_paymentmethodappinpaymentsentity
from ..shared import paymentmethodcardinpaymentsentity as shared_paymentmethodcardinpaymentsentity
from ..shared import paymentmethodcardlessemiinpaymentsentity as shared_paymentmethodcardlessemiinpaymentsentity
from ..shared import paymentmethodnetbankinginpaymentsentity as shared_paymentmethodnetbankinginpaymentsentity
from ..shared import paymentmethodpaylaterinpaymentsentity as shared_paymentmethodpaylaterinpaymentsentity
from ..shared import paymentmethodupiinpaymentsentity as shared_paymentmethodupiinpaymentsentity
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils
from typing import Optional, Union



@dataclasses.dataclass
class PaymentMethodInPaymentsEntityPaymentMethod:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PaymentMethodInPaymentsEntity:
    payment_method: Optional[Union[shared_paymentmethodcardinpaymentsentity.PaymentMethodCardInPaymentsEntity, shared_paymentmethodnetbankinginpaymentsentity.PaymentMethodNetBankingInPaymentsEntity, shared_paymentmethodupiinpaymentsentity.PaymentMethodUPIInPaymentsEntity, shared_paymentmethodappinpaymentsentity.PaymentMethodAppInPaymentsEntity, shared_paymentmethodcardlessemiinpaymentsentity.PaymentMethodCardlessEMIInPaymentsEntity, shared_paymentmethodpaylaterinpaymentsentity.PaymentMethodPaylaterInPaymentsEntity]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_method'), 'exclude': lambda f: f is None }})
    

