"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from pg_latest import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TerminalDetails:
    terminal_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_id') }})
    r"""The internal id that you use to map the terminal in your internal system"""
    terminal_phone_no: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_phone_no') }})
    r"""Phone no assigned to the terminal"""
    terminal_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('terminal_type') }})
    r"""To identify the type of terminal product in use, in this case it is SPOS"""
    

